### ISSUE TITLE
[FEATURE REQUEST] Upgrade to .NET Core 3.1

### ISSUE THREAD

**Issue by kmahon37** [kmahon37/plex-dvr-waker#11]
**Is your feature request related to a problem? Please describe.**
Need to upgrade to .NET Core 3.1 since 2.2 is no longer supported.

**Describe the solution you'd like**
The next major version of Plex DVR Waker should support .NET Core 3.1

**Comment by JWohlgem** [comment]
I agree, since 2.2 is end-of-lifed.  Until .NET Core 3.1 is supported it would also be helpful to revise the readme to point at the archived link for installing 2.2, since the current link doesn't offer a download for the 2.2 runtime.

**Comment by kmahon37** [comment]
Good suggestion, thanks.  I've updated the readme to point to the .NET Core 2.2 archive for now until I can support .NET Core 3.1.

**Comment by kmahon37** [comment]
Plex DVR Waker 2.0.0 now supports .NET Core 3.1

**Comment by JWohlgem** [comment]
This is great, I upgraded and so far so good.  Thanks!
