### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by humphreysl** [kmahon37/plex-dvr-waker#30]
**Describe the bug**
The device does not wake up as scheduled with error "0x800710e0".

**To Reproduce**
Any scheduled recording updates the Task. Put the Plex Media Server to Sleep (not Hibernate). Device does not wake as scheduled, and when manually turning on, the above error is logged against the task.

**Expected behavior**
Device to wake as scheduled and error code to be 0x0.

**Desktop (please complete the following information):**
 - Plex DVR Waker version: 2.1.1
 - Windows version: Windows 10 Version 21H2
 - .NET Core version: 3.1.21

**Additional context**
The above error suggest some sort of Permissions issue with the Scheduled Task setup. Perhaps the Task needs tweaking to be able to elevate correctly and wake the device?

UPDATE 7/12/2021 @ 19:30 - I can confirm the issue is resolved. The problem was caused by the default Windows Power Profile not allowing Wake Timers. For the set Power Profile, under Sleep > Allow wake timers (set to Enabled to resolve). Your Tasks then work as expected. You can close the Bug request.

Brilliant little App by the way!

Thanks,
Lee

**Comment by kmahon37** [comment]
Glad you were able to figure out the problem, and thanks for letting me know the resolution.

**Comment by humphreysl** [comment]
It might be worth adding that to your Installation notes so that other Users are aware that this needs to be in place?


Thanks,
Lee

________________________________

**Comment by kmahon37** [comment]
Yep, good idea.  README file is now updated.

**Comment by humphreysl** [comment]
That's great, thank you.

Once again, brilliant little tool!


Lee

________________________________
