### ISSUE TITLE
[BUG] error when setup version-check

### ISSUE THREAD

**Issue by wilsonlei** [kmahon37/plex-dvr-waker#31]
Error when setting up version check task. 

Version 2.1.1 windows 10

Command: **PlexDvrWaker.exe add-task --version-check**

Error Response: 
PlexDvrWaker 2.1.1
Copyright (C) 2020 Kris Mahon

ERROR(S):
  Error setting value to option 'offset': The 'offset' option is not compatible with 'version-check'. (Parameter
  'offset')

**Comment by kmahon37** [comment]
Thank you for reporting this.  This has been fixed in v2.1.2
